openapi: 3.0.3
info:
  title: Template Management API
  description: API for managing document templates and template rendering
  version: 1.0.0
  license:
    name: Prisa Media
    url: https://www.prisa.com/es
  contact:
    email: multimediadesarrollo@prisamedia.com
servers:
  - url: https://des-mediaservices.prisamedia.com/template-management/v1
    description: Development Server
  - url: https://des-mediaservices.prisamedia.com/template-management/v1
    description: Production Server
tags:
  - name: Templates
    description: Manage document templates
  - name: Rendering
    description: Template rendering operations
  - name: Health
    description: Service health monitoring
paths:
  /templates:
    get:
      tags:
        - Templates
      summary: List all templates
      description: Retrieve a list of all available templates
      operationId: listTemplates
      parameters:
        - name: limit
          in: query
          description: Maximum number of templates to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: offset
          in: query
          description: Number of templates to skip
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: category
          in: query
          description: Filter by template category
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Templates retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Template'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:region:lambda:path/2015-03-31/functions/function-arn/invocations"
    post:
      tags:
        - Templates
      summary: Create a new template
      description: Create a new document template
      operationId: createTemplate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTemplateRequest'
      responses:
        '201':
          description: Template created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:region:lambda:path/2015-03-31/functions/function-arn/invocations"

  /templates/{templateId}:
    get:
      tags:
        - Templates
      summary: Get template by ID
      description: Retrieve a specific template by its ID
      operationId: getTemplateById
      parameters:
        - name: templateId
          in: path
          description: ID of the template to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Template retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
        '404':
          description: Template not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:region:lambda:path/2015-03-31/functions/function-arn/invocations"
    put:
      tags:
        - Templates
      summary: Update template
      description: Update an existing template
      operationId: updateTemplate
      parameters:
        - name: templateId
          in: path
          description: ID of the template to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTemplateRequest'
      responses:
        '200':
          description: Template updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Template not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:region:lambda:path/2015-03-31/functions/function-arn/invocations"
    delete:
      tags:
        - Templates
      summary: Delete template
      description: Delete a specific template
      operationId: deleteTemplate
      parameters:
        - name: templateId
          in: path
          description: ID of the template to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Template deleted successfully
        '404':
          description: Template not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:region:lambda:path/2015-03-31/functions/function-arn/invocations"

  /templates/{templateId}/render:
    post:
      tags:
        - Rendering
      summary: Render template
      description: Render a template with provided data
      operationId: renderTemplate
      parameters:
        - name: templateId
          in: path
          description: ID of the template to render
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RenderTemplateRequest'
      responses:
        '200':
          description: Template rendered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RenderedTemplate'
            text/html:
              schema:
                type: string
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Template not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:region:lambda:path/2015-03-31/functions/function-arn/invocations"

  /health:
    get:
      tags:
        - Health
      summary: Health check
      description: Check service health status
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2023-11-26T12:00:00Z"
        '500':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:region:lambda:path/2015-03-31/functions/function-arn/invocations"

components:
  schemas:
    Template:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the template
          example: "template-123"
        name:
          type: string
          description: Name of the template
          example: "Invoice Template"
        description:
          type: string
          description: Description of the template
          example: "Standard invoice template for billing"
        category:
          type: string
          description: Category of the template
          example: "billing"
        content:
          type: string
          description: Template content with placeholders
          example: "<h1>{{title}}</h1><p>{{content}}</p>"
        format:
          type: string
          enum: ["html", "pdf", "docx", "txt"]
          description: Output format of the template
          example: "html"
        variables:
          type: array
          items:
            $ref: '#/components/schemas/TemplateVariable'
          description: List of variables used in the template
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          example: "2023-11-26T12:00:00Z"
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2023-11-26T12:00:00Z"

    TemplateVariable:
      type: object
      properties:
        name:
          type: string
          description: Variable name
          example: "title"
        type:
          type: string
          enum: ["string", "number", "boolean", "date", "array", "object"]
          description: Variable type
          example: "string"
        required:
          type: boolean
          description: Whether the variable is required
          example: true
        defaultValue:
          type: string
          description: Default value for the variable
          example: "Default Title"
        description:
          type: string
          description: Description of the variable
          example: "Document title"

    CreateTemplateRequest:
      type: object
      required:
        - name
        - content
        - format
      properties:
        name:
          type: string
          description: Name of the template
          example: "Invoice Template"
        description:
          type: string
          description: Description of the template
          example: "Standard invoice template for billing"
        category:
          type: string
          description: Category of the template
          example: "billing"
        content:
          type: string
          description: Template content with placeholders
          example: "<h1>{{title}}</h1><p>{{content}}</p>"
        format:
          type: string
          enum: ["html", "pdf", "docx", "txt"]
          description: Output format of the template
          example: "html"
        variables:
          type: array
          items:
            $ref: '#/components/schemas/TemplateVariable'
          description: List of variables used in the template

    UpdateTemplateRequest:
      type: object
      properties:
        name:
          type: string
          description: Name of the template
          example: "Invoice Template"
        description:
          type: string
          description: Description of the template
          example: "Standard invoice template for billing"
        category:
          type: string
          description: Category of the template
          example: "billing"
        content:
          type: string
          description: Template content with placeholders
          example: "<h1>{{title}}</h1><p>{{content}}</p>"
        format:
          type: string
          enum: ["html", "pdf", "docx", "txt"]
          description: Output format of the template
          example: "html"
        variables:
          type: array
          items:
            $ref: '#/components/schemas/TemplateVariable'
          description: List of variables used in the template

    RenderTemplateRequest:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          description: Data to populate the template variables
          example:
            title: "Monthly Invoice"
            content: "This is your monthly invoice for services rendered."
            amount: 1500.00
        outputFormat:
          type: string
          enum: ["html", "pdf", "docx", "txt"]
          description: Desired output format (overrides template default)
          example: "pdf"

    RenderedTemplate:
      type: object
      properties:
        templateId:
          type: string
          description: ID of the rendered template
          example: "template-123"
        content:
          type: string
          description: Rendered content
          example: "<h1>Monthly Invoice</h1><p>This is your monthly invoice for services rendered.</p>"
        format:
          type: string
          description: Output format
          example: "html"
        renderedAt:
          type: string
          format: date-time
          description: Rendering timestamp
          example: "2023-11-26T12:00:00Z"

    Pagination:
      type: object
      properties:
        currentPage:
          type: integer
          description: Current page number
          example: 1
        totalPages:
          type: integer
          description: Total number of pages
          example: 10
        perPageElements:
          type: integer
          description: Number of elements per page
          example: 20
        totalElements:
          type: integer
          description: Total number of elements
          example: 200

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Error code
          example: "TEMPLATE_NOT_FOUND"
        message:
          type: string
          description: Error message
          example: "The requested template was not found"
        details:
          type: array
          items:
            type: string
          description: Additional error details
          example: ["Template ID: template-123 does not exist"]
